# workflow name
name: conditionals
# event 
on: 
  push:
    branches:
      - master
# jobs
jobs:
  regular_job:
    # github context => contains info about the workflow run and the event that triggered the run 
    # github.ref => refers to the branch/tag that triggered the workflow run
    # note that github performs loose equality => which means instead of "!==", need to use "!="
    if: ${{ github.ref != "refs/heads/master" }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Regular job"
  special_job:
    if: contains(github.ref, "master")
    runs-on: ubuntu-latest
    steps:
      - run: echo "Special job"