name: conditionals-steps
on:
  push:
    branches:
      - master
jobs:
  regular_job:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Regular step"
      - name: Success notification
        # returns true if none of the previous steps have failed
        if: ${{ success() }}
        run: echo "Success"
      - name: Failure notification
        # returns true if any of the previous steps have failed
        if: ${{ failure() }}
        run: echo "Failure"

