name: dependent-jobs
on:
  push:
    branches:
      - master
jobs:
  build_a: 
    runs-on: ubuntu-latest
    steps:
      - name: Force fail
        run: exit 1
      - run: echo "This job will be run first"

  build_b:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This job will be run first, in parallel with build_a" 

  build_c:
    runs-on: ubuntu-latest
    needs: [build_a, build_b]
    steps:
      - run: echo "This job needs build_a and build_b to finish running before it can run"
  
  build_d:
    runs-on: ubuntu-latest
    needs: [build_b]
    steps:
      - run: echo "This job only needs build_b to finish running before it can run"