# workflow name
name: variables-secrets
# event
on: 
  push:
    branches:
      - master
# environment variables that are available to all jobs in the workflow
env:
  BAZ_VARIABLE: BAZ
# jobs
jobs:
  variables-secrets-1:
    runs-on: ubuntu-latest
    # environment variables that are only available to this job 
    env:
      BAR_VARIABLE: BAR
    steps:
      - name: Retrieve secret via an env var
        # to make the secret available on an action, must set the secret as an input or environment variable in the workflow file
        env:
          EXAMPLE_API_KEY: ${{ secrets.EXAMPLE_API_KEY }}
          FOO_VARIABLE: FOO
        run: echo "$EXAMPLE_API_KEY $FOO_VARIABLE BAZ_VARIABLE"
      - name: Directly retrieve a secret
        run: echo "${{ secrets.EXAMPLE_API_KEY }} ${{ env.BAR_VARIABLE }}"
  
    
      